Final Try with 2.0.1

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -8,91 +8,91 @@ workflows:
     jobs:
       - waiter
       # - qa-ui:
-      #     name: qa-ui-regression-celery-2.0.0-buster
-      #     airflow_version: 2.0.0
+      #     name: qa-ui-regression-celery-2.0.1-buster
+      #     airflow_version: 2.0.1
       #     dev_build: true
-      #     extra_tags: "2.0.0-buster-onbuild-${CIRCLE_BUILD_NUM}"
+      #     extra_tags: "2.0.1-buster-onbuild-${CIRCLE_BUILD_NUM}"
       #     executor_type: "celery"
       #     test_type: "testim"
       #     requires:
       #       - waiter
       # - qa-ui:
-      #     name: qa-ui-regression-k8s-2.0.0-buster
-      #     airflow_version: 2.0.0
+      #     name: qa-ui-regression-k8s-2.0.1-buster
+      #     airflow_version: 2.0.1
       #     dev_build: true
-      #     extra_tags: "2.0.0-buster-onbuild-${CIRCLE_BUILD_NUM}"
+      #     extra_tags: "2.0.1-buster-onbuild-${CIRCLE_BUILD_NUM}"
       #     executor_type: "kubernetes"
       #     test_type: "testim"
       #     requires:
       #       - waiter
       # - qa-ui:
-      #     name: qa-ui-regression-k8s-2.0.0-buster
-      #     airflow_version: 2.0.0
+      #     name: qa-ui-regression-k8s-2.0.1-buster
+      #     airflow_version: 2.0.1
       #     dev_build: true
-      #     extra_tags: "2.0.0-buster-onbuild-${CIRCLE_BUILD_NUM}"
+      #     extra_tags: "2.0.1-buster-onbuild-${CIRCLE_BUILD_NUM}"
       #     executor_type: "kubernetes"
       #     test_type: "testim"
       #     requires:
       #       - waiter
       - qa-core:
-          name: qa-core-celery-2.0.0-buster
-          airflow_version: 2.0.0
+          name: qa-core-celery-2.0.1-buster
+          airflow_version: 2.0.1
           dev_build: true
-          extra_tags: "2.0.0-buster-onbuild-${CIRCLE_BUILD_NUM}"
+          extra_tags: "2.0.1-buster-onbuild-${CIRCLE_BUILD_NUM}"
           executor_type: "celery"
           test_type: "core"
           requires:
             - waiter
       # - qa-negative:
-      #     name: qa-negative-celery-2.0.0-buster
-      #     airflow_version: 2.0.0
+      #     name: qa-negative-celery-2.0.1-buster
+      #     airflow_version: 2.0.1
       #     dev_build: true
-      #     extra_tags: "2.0.0-buster-onbuild-${CIRCLE_BUILD_NUM}"
+      #     extra_tags: "2.0.1-buster-onbuild-${CIRCLE_BUILD_NUM}"
       #     executor_type: "celery"
       #     test_type: "core"
       #     requires:
       #       - qa-core
       # - qa-dagmodel:
-      #     name: qa-dagmodel-celery-2.0.0-buster
-      #     airflow_version: 2.0.0
+      #     name: qa-dagmodel-celery-2.0.1-buster
+      #     airflow_version: 2.0.1
       #     dev_build: true
-      #     extra_tags: "2.0.0-buster-onbuild-${CIRCLE_BUILD_NUM}"
+      #     extra_tags: "2.0.1-buster-onbuild-${CIRCLE_BUILD_NUM}"
       #     executor_type: "celery"
       #     test_type: "core"
       #     requires:
       #       - qa-core
       - qa-k8s:
-          name: qa-k8s-celery-2.0.0-buster
-          airflow_version: 2.0.0
+          name: qa-k8s-celery-2.0.1-buster
+          airflow_version: 2.0.1
           dev_build: true
-          extra_tags: "2.0.0-buster-onbuild-${CIRCLE_BUILD_NUM}"
+          extra_tags: "2.0.1-buster-onbuild-${CIRCLE_BUILD_NUM}"
           executor_type: "celery"
           test_type: "core"
           requires:
-            - qa-core-celery-2.0.0-buster
+            - qa-core-celery-2.0.1-buster
       - qa-restapi:
-          name: qa-restapi-2.0.0-buster
-          airflow_version: 2.0.0
+          name: qa-restapi-2.0.1-buster
+          airflow_version: 2.0.1
           dev_build: true
-          extra_tags: "2.0.0-buster-onbuild-${CIRCLE_BUILD_NUM}"
+          extra_tags: "2.0.1-buster-onbuild-${CIRCLE_BUILD_NUM}"
           executor_type: "celery"
           test_type: "core"
           requires:
             - waiter
       # - qa-core:
-      #     name: qa-core-k8s-2.0.0-buster
-      #     airflow_version: 2.0.0
+      #     name: qa-core-k8s-2.0.1-buster
+      #     airflow_version: 2.0.1
       #     dev_build: true
-      #     extra_tags: "2.0.0-buster-onbuild-${CIRCLE_BUILD_NUM}"
+      #     extra_tags: "2.0.1-buster-onbuild-${CIRCLE_BUILD_NUM}"
       #     executor_type: "kubernetes"
       #     test_type: "core"
       #     requires:
       #       - waiter
       # - qa-core:
-      #     name: qa-core-local-2.0.0-buster
-      #     airflow_version: 2.0.0
+      #     name: qa-core-local-2.0.1-buster
+      #     airflow_version: 2.0.1
       #     dev_build: true
-      #     extra_tags: "2.0.0-buster-onbuild-${CIRCLE_BUILD_NUM}"
+      #     extra_tags: "2.0.1-buster-onbuild-${CIRCLE_BUILD_NUM}"
       #     executor_type: "local"
       #     test_type: "core"
       #     requires:
@@ -101,57 +101,57 @@ workflows:
     jobs:
       - static-checks
       - build:
-          name: build-2.0.0-buster
-          airflow_version: 2.0.0
+          name: build-2.0.1-buster
+          airflow_version: 2.0.1
           distribution_name: buster
           dev_build: true
-          extra_args: "--build-arg VERSION=$(curl https://pip.astronomer.io/simple/astronomer-certified/latest-2.0.0.build)"
+          extra_args: "--build-arg VERSION=$(curl https://pip.astronomer.io/simple/astronomer-certified/latest-2.0.1.build)"
           requires:
             - static-checks
       # - scan-clair:
-      #     name: scan-clair-2.0.0-buster-onbuild
-      #     airflow_version: 2.0.0
+      #     name: scan-clair-2.0.1-buster-onbuild
+      #     airflow_version: 2.0.1
       #     distribution_name: buster-onbuild
       #     requires:
-      #       - build-2.0.0-buster
+      #       - build-2.0.1-buster
       # - scan-trivy:
-      #     name: scan-trivy-2.0.0-buster-onbuild
-      #     airflow_version: 2.0.0
+      #     name: scan-trivy-2.0.1-buster-onbuild
+      #     airflow_version: 2.0.1
       #     distribution: buster
       #     distribution_name: buster-onbuild
       #     requires:
-      #       - build-2.0.0-buster
+      #       - build-2.0.1-buster
       - test:
-          name: test-2.0.0-buster-images
-          tag: "2.0.0-buster"
+          name: test-2.0.1-buster-images
+          tag: "2.0.1-buster"
           requires:
-            - build-2.0.0-buster
+            - build-2.0.1-buster
       - push:
-          name: push-2.0.0-buster
-          tag: "2.0.0-buster"
+          name: push-2.0.1-buster
+          tag: "2.0.1-buster"
           dev_build: true
-          extra_tags: "2.0.0-buster-${CIRCLE_BUILD_NUM},2.0.0-2.dev-buster"
+          extra_tags: "2.0.1-buster-${CIRCLE_BUILD_NUM},2.0.1-1.dev-buster"
           context:
             - quay.io
           requires:
-            # - scan-clair-2.0.0-buster-onbuild
-            # - scan-trivy-2.0.0-buster-onbuild
-            - test-2.0.0-buster-images
+            # - scan-clair-2.0.1-buster-onbuild
+            # - scan-trivy-2.0.1-buster-onbuild
+            - test-2.0.1-buster-images
           filters:
             branches:
               only:
                 - master
       - push:
-          name: push-2.0.0-buster-onbuild
-          tag: "2.0.0-buster-onbuild"
+          name: push-2.0.1-buster-onbuild
+          tag: "2.0.1-buster-onbuild"
           dev_build: true
-          extra_tags: "2.0.0-buster-onbuild-${CIRCLE_BUILD_NUM},2.0.0-2.dev-buster-onbuild"
+          extra_tags: "2.0.1-buster-onbuild-${CIRCLE_BUILD_NUM},2.0.1-1.dev-buster-onbuild"
           context:
             - quay.io
           requires:
-            # - scan-clair-2.0.0-buster-onbuild
-            # - scan-trivy-2.0.0-buster-onbuild
-            - test-2.0.0-buster-images
+            # - scan-clair-2.0.1-buster-onbuild
+            # - scan-trivy-2.0.1-buster-onbuild
+            - test-2.0.1-buster-images
           filters:
             branches:
               only:
@@ -167,55 +167,55 @@ workflows:
                 - master
     jobs:
       - build:
-          name: build-2.0.0-buster
-          airflow_version: 2.0.0
+          name: build-2.0.1-buster
+          airflow_version: 2.0.1
           distribution_name: buster
           dev_build: true
-          extra_args: "--build-arg VERSION=$(curl https://pip.astronomer.io/simple/astronomer-certified/latest-2.0.0.build)"
+          extra_args: "--build-arg VERSION=$(curl https://pip.astronomer.io/simple/astronomer-certified/latest-2.0.1.build)"
       # - scan-clair:
-      #     name: scan-clair-2.0.0-buster-onbuild
-      #     airflow_version: 2.0.0
+      #     name: scan-clair-2.0.1-buster-onbuild
+      #     airflow_version: 2.0.1
       #     distribution_name: buster-onbuild
       #     requires:
-      #       - build-2.0.0-buster
+      #       - build-2.0.1-buster
       # - scan-trivy:
-      #     name: scan-trivy-2.0.0-buster-onbuild
-      #     airflow_version: 2.0.0
+      #     name: scan-trivy-2.0.1-buster-onbuild
+      #     airflow_version: 2.0.1
       #     distribution: buster
       #     distribution_name: buster-onbuild
       #     requires:
-      #       - build-2.0.0-buster
+      #       - build-2.0.1-buster
       - test:
-          name: test-2.0.0-buster-images
-          tag: "2.0.0-buster"
+          name: test-2.0.1-buster-images
+          tag: "2.0.1-buster"
           requires:
-            - build-2.0.0-buster
+            - build-2.0.1-buster
       - push:
-          name: push-2.0.0-buster
-          tag: "2.0.0-buster"
+          name: push-2.0.1-buster
+          tag: "2.0.1-buster"
           dev_build: true
-          extra_tags: "2.0.0-buster-${CIRCLE_BUILD_NUM}"
+          extra_tags: "2.0.1-buster-${CIRCLE_BUILD_NUM}"
           context:
             - quay.io
           requires:
-            # - scan-clair-2.0.0-buster-onbuild
-            # - scan-trivy-2.0.0-buster-onbuild
-            - test-2.0.0-buster-images
+            # - scan-clair-2.0.1-buster-onbuild
+            # - scan-trivy-2.0.1-buster-onbuild
+            - test-2.0.1-buster-images
           filters:
             branches:
               only:
                 - master
       - push:
-          name: push-2.0.0-buster-onbuild
-          tag: "2.0.0-buster-onbuild"
+          name: push-2.0.1-buster-onbuild
+          tag: "2.0.1-buster-onbuild"
           dev_build: true
-          extra_tags: "2.0.0-buster-onbuild-${CIRCLE_BUILD_NUM},2.0.0-2.dev-buster-onbuild"
+          extra_tags: "2.0.1-buster-onbuild-${CIRCLE_BUILD_NUM},2.0.1-1.dev-buster-onbuild"
           context:
             - quay.io
           requires:
-            # - scan-clair-2.0.0-buster-onbuild
-            # - scan-trivy-2.0.0-buster-onbuild
-            - test-2.0.0-buster-images
+            # - scan-clair-2.0.1-buster-onbuild
+            # - scan-trivy-2.0.1-buster-onbuild
+            - test-2.0.1-buster-images
           filters:
             branches:
               only:
@@ -347,14 +347,14 @@ jobs:
             pip3 install -e .
             python3 -m venv env
             . env/bin/activate
-            fileurl="/home/circle/project/env_current_api_url"
+            fileurl="/home/circleci/project/env_current_api_url"
             export AIRFLOW_API_URL=$(cat "$fileurl")
             export DAGSTEST_DB_HOST=suleiman.db.elephantsql.com
             export DAGSTEST_DB_PORT=5432
             export DAGSTEST_DB_NAME=axsrggsp
             export DAGSTEST_DB_USER=axsrggsp
             export DAGSTEST_DB_PASSWORD=$QA_DAGSTEST_DB_PASSWORD
-            dags connections --headers "Authorization":"Bearer $QA_CLUSTER_SERVICEACCOUNT" -f airflow_settings.yaml
+            dags connections --headers "Authorization":"Bearer $QA_CLUSTER_SERVICEACCOUNT" -f /home/circleci/project/qa-scenario-dags/airflow_settings.yaml
             EXEC_TIME=$(date +%FT%TZ)
             dags trigger --headers "Authorization":"$QA_CLUSTER_SERVICEACCOUNT" -e $EXEC_TIME -t core
             sleep 240
@@ -422,8 +422,12 @@ jobs:
             chmod 744 run_restapi_smoke.sh
             bash ./run_restapi_smoke.sh
             cp result.out /tmp/test-results/restapi/
-            grep -q "404 Not Found" result.out && exit 1
-            grep -q "500 INTERNAL SERVER ERROR" result.out && exit 1
+            FOUND_404=0
+            FOUND_500=0
+            grep -q "404 Not Found" result.out && FOUND_404=1
+            grep -q "500 INTERNAL SERVER ERROR" result.out && FOUND_500=1
+            if [[ "$FOUND_404" -eq 1 ]]; then echo "404 Errors Found";exit 1; fi
+            if [[ "$FOUND_500" -eq 1 ]]; then echo "500 Errors Found";exit 1; fi
       - store_artifacts:
           path: /tmp/test-results
       - store_test_results:
@@ -491,7 +495,7 @@ jobs:
             export DAGSTEST_DB_NAME=axsrggsp
             export DAGSTEST_DB_USER=axsrggsp
             export DAGSTEST_DB_PASSWORD=$QA_DAGSTEST_DB_PASSWORD
-            dags connections --headers "Authorization":"Bearer $QA_CLUSTER_SERVICEACCOUNT" -f airflow_settings.yaml
+            dags connections --headers "Authorization":"Bearer $QA_CLUSTER_SERVICEACCOUNT" -f /home/circleci/project/qa-scenario-dags/airflow_settings.yaml
             EXEC_TIME=$(date +%FT%TZ)
             dags trigger --headers "Authorization":"$QA_CLUSTER_SERVICEACCOUNT" -e $EXEC_TIME -t k8s
             sleep 240
diff --git a/.circleci/config.yml.j2 b/.circleci/config.yml.j2
--- a/.circleci/config.yml.j2
+++ b/.circleci/config.yml.j2
@@ -370,14 +370,14 @@ jobs:
             pip3 install -e .
             python3 -m venv env
             . env/bin/activate
-            fileurl="/home/circle/project/env_current_api_url"
+            fileurl="/home/circleci/project/env_current_api_url"
             export AIRFLOW_API_URL=$(cat "$fileurl")
             export DAGSTEST_DB_HOST=suleiman.db.elephantsql.com
             export DAGSTEST_DB_PORT=5432
             export DAGSTEST_DB_NAME=axsrggsp
             export DAGSTEST_DB_USER=axsrggsp
             export DAGSTEST_DB_PASSWORD=$QA_DAGSTEST_DB_PASSWORD
-            dags connections --headers "Authorization":"Bearer $QA_CLUSTER_SERVICEACCOUNT" -f airflow_settings.yaml
+            dags connections --headers "Authorization":"Bearer $QA_CLUSTER_SERVICEACCOUNT" -f /home/circleci/project/qa-scenario-dags/airflow_settings.yaml
             EXEC_TIME=$(date +%FT%TZ)
             dags trigger --headers "Authorization":"$QA_CLUSTER_SERVICEACCOUNT" -e $EXEC_TIME -t core
             sleep 240
@@ -445,8 +445,12 @@ jobs:
             chmod 744 run_restapi_smoke.sh
             bash ./run_restapi_smoke.sh
             cp result.out /tmp/test-results/restapi/
-            grep -q "404 Not Found" result.out && exit 1
-            grep -q "500 INTERNAL SERVER ERROR" result.out && exit 1
+            FOUND_404=0
+            FOUND_500=0
+            grep -q "404 Not Found" result.out && FOUND_404=1
+            grep -q "500 INTERNAL SERVER ERROR" result.out && FOUND_500=1
+            if [[ "$FOUND_404" -eq 1 ]]; then echo "404 Errors Found";exit 1; fi
+            if [[ "$FOUND_500" -eq 1 ]]; then echo "500 Errors Found";exit 1; fi
       - store_artifacts:
           path: /tmp/test-results
       - store_test_results:
@@ -514,7 +518,7 @@ jobs:
             export DAGSTEST_DB_NAME=axsrggsp
             export DAGSTEST_DB_USER=axsrggsp
             export DAGSTEST_DB_PASSWORD=$QA_DAGSTEST_DB_PASSWORD
-            dags connections --headers "Authorization":"Bearer $QA_CLUSTER_SERVICEACCOUNT" -f airflow_settings.yaml
+            dags connections --headers "Authorization":"Bearer $QA_CLUSTER_SERVICEACCOUNT" -f /home/circleci/project/qa-scenario-dags/airflow_settings.yaml
             EXEC_TIME=$(date +%FT%TZ)
             dags trigger --headers "Authorization":"$QA_CLUSTER_SERVICEACCOUNT" -e $EXEC_TIME -t k8s
             sleep 240
