test

diff --git a/.circleci/config.yml.j2 b/.circleci/config.yml.j2
--- a/.circleci/config.yml.j2
+++ b/.circleci/config.yml.j2
@@ -432,9 +432,9 @@ jobs:
             # grep -q "failed" /tmp/test-results/results_core_dags.out && FOUND_FAILURES=1
             # cat /tmp/test-results/results_core_dags.out
             # if [[ "$FOUND_FAILURES" -eq 1 ]]; then echo "DAG Failures Found";exit 1; fi
-            cd /home/circleci/project/qa-regression
-            chmod 744 delete_deployment.sh
-            bash ./delete_deployment.sh
+            # cd /home/circleci/project/qa-regression
+            # chmod 744 delete_deployment.sh
+            # bash ./delete_deployment.sh
       - store_artifacts:
           path: /tmp/test-results
       - store_test_results:
@@ -496,19 +496,19 @@ jobs:
             cd /home/circleci/project/qa-regression/postman_rest
             chmod 744 run_restapi_smoke.sh
             bash ./run_restapi_smoke.sh
-            cp result.out /tmp/test-results/restapi/
-            FOUND_404=0
-            FOUND_500=0
-            ASSERTION_ERRORS=0
-            grep -q "404 Not Found" result.out && FOUND_404=1
-            grep -q "500 INTERNAL SERVER ERROR" result.out && FOUND_500=1
-            grep -q "AssertionError" result.out && ASSERTION_ERRORS=1
-            if [[ "$FOUND_404" -eq 1 ]]; then echo "404 Errors Found";exit 1; fi
-            if [[ "$FOUND_500" -eq 1 ]]; then echo "500 Errors Found";exit 1; fi
-            if [[ "$ASSERTION_ERRORS" -eq 1 ]]; then echo "Assertion Errors Found";exit 1; fi
-            cd /home/circleci/project/qa-regression
-            chmod 744 delete_deployment.sh
-            bash ./delete_deployment.sh
+            #cp result.out /tmp/test-results/restapi/
+            #FOUND_404=0
+            #FOUND_500=0
+            #ASSERTION_ERRORS=0
+            #grep -q "404 Not Found" result.out && FOUND_404=1
+            #grep -q "500 INTERNAL SERVER ERROR" result.out && FOUND_500=1
+            #grep -q "AssertionError" result.out && ASSERTION_ERRORS=1
+            #if [[ "$FOUND_404" -eq 1 ]]; then echo "404 Errors Found";exit 1; fi
+            #if [[ "$FOUND_500" -eq 1 ]]; then echo "500 Errors Found";exit 1; fi
+            #if [[ "$ASSERTION_ERRORS" -eq 1 ]]; then echo "Assertion Errors Found";exit 1; fi
+            #cd /home/circleci/project/qa-regression
+            #chmod 744 delete_deployment.sh
+            #bash ./delete_deployment.sh
       - store_artifacts:
           path: /tmp/test-results
       - store_test_results:
@@ -592,9 +592,9 @@ jobs:
             # grep -q "failed" /tmp/test-results/results_k8s_dags.out && FOUND_FAILURES=1
             # cat /tmp/test-results/results_k8s_dags.out
             # if [[ "$FOUND_FAILURES" -eq 1 ]]; then echo "DAG Failures Found1";exit 1; fi
-            cd /home/circleci/project/qa-regression
-            chmod 744 delete_deployment.sh
-            bash ./delete_deployment.sh
+            # cd /home/circleci/project/qa-regression
+            # chmod 744 delete_deployment.sh
+            # bash ./delete_deployment.sh
       - store_artifacts:
           path: /tmp/test-results
       - store_test_results:
@@ -669,16 +669,100 @@ jobs:
             #dags connections --headers "Authorization":"Bearer $QA_CLUSTER_SERVICEACCOUNT" -f /home/circleci/project/qa-scenario-dags/airflow_settings.yaml
             EXEC_TIME=$(date +%FT%TZ)
             dags trigger --headers "Authorization":"$QA_CLUSTER_SERVICEACCOUNT" -e $EXEC_TIME -t negative
-            sleep 240
+            sleep 500
             echo "Sleeping for 240s"
             dags results -e $EXEC_TIME --headers "Authorization":"Bearer $QA_CLUSTER_SERVICEACCOUNT" > $CORE_TEST_REPORTS/k8s/results_k8s_dags.out
             # FOUND_FAILURES=0
             # grep -q "failed" /tmp/test-results/results_k8s_dags.out && FOUND_FAILURES=1
             # cat /tmp/test-results/results_k8s_dags.out
             # if [[ "$FOUND_FAILURES" -eq 1 ]]; then echo "DAG Failures Found1";exit 1; fi
-            cd /home/circleci/project/qa-regression
-            chmod 744 delete_deployment.sh
-            bash ./delete_deployment.sh
+            # cd /home/circleci/project/qa-regression
+            # chmod 744 delete_deployment.sh
+            # bash ./delete_deployment.sh
+      - store_artifacts:
+          path: /tmp/test-results
+      - store_test_results:
+          path: /tmp/test-results
+      - persist_to_workspace:
+          root: .
+          paths:
+            - project
+  qa-params:
+    description: "Run the DAG Parameters"
+    environment:
+      CORE_TEST_REPORTS: /tmp/test-results
+    machine: # executor type
+      image: ubuntu-2004:202010-01
+    parameters:
+      airflow_version:
+        description: "The Airflow version, for example '1.10.5'"
+        type: string
+      dev_build:
+        description: "Indicate if this is a dev build"
+        type: boolean
+      extra_tags:
+        description: "Extra args to pass to pass to Docker build command"
+        type: string
+      executor_type:
+        description: "The type of executor to run on"
+        default: "celery"
+        type: string
+      test_type:
+        description: "The type of framework to run"
+        default: ""
+        type: string
+    steps:
+      - attach_workspace:
+          at: ~/
+      # - run: sudo apt-get -y update
+      # - run: sudo apt-get -y install git curl wget libpq-dev nodejs
+      # - run: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
+      # - run: npm -v
+      # - run: node -v
+      # - run:
+      #     name: Avoid hosts unknown for github
+      #     command:   |
+      #       [ ! -d ~/.ssh ] && mkdir ~/.ssh/
+      #       echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
+      # - run: git clone git@github.com:astronomer/qa-regression.git
+      # - run: git clone git@github.com:astronomer/qa-scenario-dags.git
+      # - run:
+      #     name: Run Shell Script for creating deployments
+      #     command:  |
+      #       cd qa-regression
+      #       ls
+      #       chmod 744 *.sh
+      #       echo "Run Deployment Script"
+      #       bash ./create_deployment.sh << parameters.airflow_version >>  << parameters.executor_type >>  << parameters.test_type >>
+      #       cd ..
+      - run: mkdir -p $CORE_TEST_REPORTS/dag-params
+      - run:
+          name: Run the DAGS
+          command:   |
+            cd /home/circleci/project/qa-scenario-dags/scripts/dagstest
+            pip3 install -e .
+            python3 -m venv env
+            . env/bin/activate
+            fileurl="/home/circle/project/env_current_api_url"
+            export AIRFLOW_API_URL=$(cat "$fileurl")
+            export DAGSTEST_DB_HOST=suleiman.db.elephantsql.com
+            export DAGSTEST_DB_PORT=5432
+            export DAGSTEST_DB_NAME=axsrggsp
+            export DAGSTEST_DB_USER=axsrggsp
+            export DAGSTEST_DB_PASSWORD=$QA_DAGSTEST_DB_PASSWORD
+            #dags connections --headers "Authorization":"Bearer $QA_CLUSTER_SERVICEACCOUNT" -f /home/circleci/project/qa-scenario-dags/airflow_settings.yaml
+            EXEC_TIME=$(date +%FT%TZ)
+            dags trigger --headers "Authorization":"$QA_CLUSTER_SERVICEACCOUNT" -e $EXEC_TIME -t dagparams
+            sleep 500
+            echo "Sleeping for 240s"
+            dags results -e $EXEC_TIME --headers "Authorization":"Bearer $QA_CLUSTER_SERVICEACCOUNT" > $CORE_TEST_REPORTS/dag-params/results_dag-params_dags.out
+            # FOUND_FAILURES=0
+            # grep -q "failed" /tmp/test-results/results_dag-params_dags.out && FOUND_FAILURES=1
+            # cat /tmp/test-results/results_dag-params_dags.out
+            # if [[ "$FOUND_FAILURES" -eq 1 ]]; then echo "DAG Failures Found1";exit 1; fi
+            # cd /home/circleci/project/qa-regression
+            # chmod 744 delete_deployment.sh
+            # bash ./delete_deployment.sh
       - store_artifacts:
           path: /tmp/test-results
       - store_test_results:
