Export to Tesults

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -3,538 +3,6 @@
 version: 2.1
 
 workflows:
-  regression-2.0.0-buster:
-    jobs:
-      - waiter:
-          name: waiter-2.0.0-buster
-          airflow_version: 2.0.0
-          context:
-            - qa
-      - qa-ui:
-          name: qa-ui-regression-celery-2.0.0-buster
-          airflow_version: 2.0.0
-          executor_type: "celery"
-          test_type: "testim"
-          requires:
-            - waiter-2.0.0-buster
-          context:
-            - qa
-      - qa-ui:
-          name: qa-ui-regression-k8s-2.0.0-buster
-          airflow_version: 2.0.0
-          executor_type: "kubernetes"
-          test_type: "testim"
-          requires:
-            - qa-ui-regression-celery-2.0.0-buster
-          context:
-            - qa
-      - qa-ui:
-          name: qa-ui-regression-local-2.0.0-buster
-          airflow_version: 2.0.0
-          executor_type: "local"
-          test_type: "testim"
-          requires:
-            - qa-ui-regression-k8s-2.0.0-buster
-          context:
-            - qa
-      - qa-core:
-          name: qa-core-celery-2.0.0-buster
-          airflow_version: 2.0.0
-          executor_type: "celery"
-          test_type: "core"
-          requires:
-            - waiter-2.0.0-buster
-          context:
-            - qa
-      - qa-k8s:
-          name: qa-k8s-celery-2.0.0-buster
-          airflow_version: 2.0.0
-          executor_type: "celery"
-          test_type: "k8s"
-          requires:
-            - qa-core-celery-2.0.0-buster
-          context:
-            - qa
-      - qa-params:
-          name: qa-params-celery-2.0.0-buster
-          airflow_version: 2.0.0
-          executor_type: "celery"
-          test_type: "dagparams"
-          requires:
-            - qa-core-celery-2.0.0-buster
-          context:
-            - qa
-      - qa-restapi:
-          name: qa-restapi-celery-2.0.0-buster
-          airflow_version: 2.0.0
-          executor_type: "celery"
-          test_type: "rest"
-          requires:
-            - waiter-2.0.0-buster
-          context:
-            - qa
-      - qa-restapi:
-          name: qa-restapi-local-2.0.0-buster
-          airflow_version: 2.0.0
-          executor_type: "local"
-          test_type: "rest"
-          requires:
-            - qa-restapi-celery-2.0.0-buster
-          context:
-            - qa
-      - qa-restapi:
-          name: qa-restapi-k8s-2.0.0-buster
-          airflow_version: 2.0.0
-          executor_type: "kubernetes"
-          test_type: "rest"
-          requires:
-            - qa-restapi-local-2.0.0-buster
-          context:
-            - qa
-      - qa-core:
-          name: qa-core-k8s-2.0.0-buster
-          airflow_version: 2.0.0
-          executor_type: "kubernetes"
-          test_type: "core"
-          requires:
-            - waiter-2.0.0-buster
-          context:
-            - qa
-      - qa-k8s:
-          name: qa-k8s-k8s-2.0.0-buster
-          airflow_version: 2.0.0
-          executor_type: "kubernetes"
-          test_type: "k8"
-          requires:
-            - qa-core-k8s-2.0.0-buster
-          context:
-            - qa
-      - qa-params:
-          name: qa-params-k8s-2.0.0-buster
-          airflow_version: 2.0.0
-          executor_type: "kubernetes"
-          test_type: "dagparams"
-          requires:
-            - qa-k8s-k8s-2.0.0-buster
-          context:
-            - qa
-      - qa-negative:
-          name: qa-negative-k8s-2.0.0-buster
-          airflow_version: 2.0.0
-          executor_type: "kubernetes"
-          test_type: "negative"
-          requires:
-            - qa-params-k8s-2.0.0-buster
-          context:
-            - qa
-      - qa-core:
-          name: qa-core-local-2.0.0-buster
-          airflow_version: 2.0.0
-          executor_type: "local"
-          test_type: "core"
-          requires:
-            - waiter-2.0.0-buster
-          context:
-            - qa
-  regression-2.0.2-buster:
-    jobs:
-      - waiter:
-          name: waiter-2.0.2-buster
-          airflow_version: 2.0.2
-          context:
-            - qa
-      - qa-ui:
-          name: qa-ui-regression-celery-2.0.2-buster
-          airflow_version: 2.0.2
-          executor_type: "celery"
-          test_type: "testim"
-          requires:
-            - waiter-2.0.2-buster
-          context:
-            - qa
-      - qa-ui:
-          name: qa-ui-regression-k8s-2.0.2-buster
-          airflow_version: 2.0.2
-          executor_type: "kubernetes"
-          test_type: "testim"
-          requires:
-            - qa-ui-regression-celery-2.0.2-buster
-          context:
-            - qa
-      - qa-ui:
-          name: qa-ui-regression-local-2.0.2-buster
-          airflow_version: 2.0.2
-          executor_type: "local"
-          test_type: "testim"
-          requires:
-            - qa-ui-regression-k8s-2.0.2-buster
-          context:
-            - qa
-      - qa-core:
-          name: qa-core-celery-2.0.2-buster
-          airflow_version: 2.0.2
-          executor_type: "celery"
-          test_type: "core"
-          requires:
-            - waiter-2.0.2-buster
-          context:
-            - qa
-      - qa-k8s:
-          name: qa-k8s-celery-2.0.2-buster
-          airflow_version: 2.0.2
-          executor_type: "celery"
-          test_type: "k8s"
-          requires:
-            - qa-core-celery-2.0.2-buster
-          context:
-            - qa
-      - qa-params:
-          name: qa-params-celery-2.0.2-buster
-          airflow_version: 2.0.2
-          executor_type: "celery"
-          test_type: "dagparams"
-          requires:
-            - qa-core-celery-2.0.2-buster
-          context:
-            - qa
-      - qa-restapi:
-          name: qa-restapi-celery-2.0.2-buster
-          airflow_version: 2.0.2
-          executor_type: "celery"
-          test_type: "rest"
-          requires:
-            - waiter-2.0.2-buster
-          context:
-            - qa
-      - qa-restapi:
-          name: qa-restapi-local-2.0.2-buster
-          airflow_version: 2.0.2
-          executor_type: "local"
-          test_type: "rest"
-          requires:
-            - qa-restapi-celery-2.0.2-buster
-          context:
-            - qa
-      - qa-restapi:
-          name: qa-restapi-k8s-2.0.2-buster
-          airflow_version: 2.0.2
-          executor_type: "kubernetes"
-          test_type: "rest"
-          requires:
-            - qa-restapi-local-2.0.2-buster
-          context:
-            - qa
-      - qa-core:
-          name: qa-core-k8s-2.0.2-buster
-          airflow_version: 2.0.2
-          executor_type: "kubernetes"
-          test_type: "core"
-          requires:
-            - waiter-2.0.2-buster
-          context:
-            - qa
-      - qa-k8s:
-          name: qa-k8s-k8s-2.0.2-buster
-          airflow_version: 2.0.2
-          executor_type: "kubernetes"
-          test_type: "k8"
-          requires:
-            - qa-core-k8s-2.0.2-buster
-          context:
-            - qa
-      - qa-params:
-          name: qa-params-k8s-2.0.2-buster
-          airflow_version: 2.0.2
-          executor_type: "kubernetes"
-          test_type: "dagparams"
-          requires:
-            - qa-k8s-k8s-2.0.2-buster
-          context:
-            - qa
-      - qa-negative:
-          name: qa-negative-k8s-2.0.2-buster
-          airflow_version: 2.0.2
-          executor_type: "kubernetes"
-          test_type: "negative"
-          requires:
-            - qa-params-k8s-2.0.2-buster
-          context:
-            - qa
-      - qa-core:
-          name: qa-core-local-2.0.2-buster
-          airflow_version: 2.0.2
-          executor_type: "local"
-          test_type: "core"
-          requires:
-            - waiter-2.0.2-buster
-          context:
-            - qa
-  regression-2.1.0-buster:
-    jobs:
-      - waiter:
-          name: waiter-2.1.0-buster
-          airflow_version: 2.1.0
-          context:
-            - qa
-      - qa-ui:
-          name: qa-ui-regression-celery-2.1.0-buster
-          airflow_version: 2.1.0
-          executor_type: "celery"
-          test_type: "testim"
-          requires:
-            - waiter-2.1.0-buster
-          context:
-            - qa
-      - qa-ui:
-          name: qa-ui-regression-k8s-2.1.0-buster
-          airflow_version: 2.1.0
-          executor_type: "kubernetes"
-          test_type: "testim"
-          requires:
-            - qa-ui-regression-celery-2.1.0-buster
-          context:
-            - qa
-      - qa-ui:
-          name: qa-ui-regression-local-2.1.0-buster
-          airflow_version: 2.1.0
-          executor_type: "local"
-          test_type: "testim"
-          requires:
-            - qa-ui-regression-k8s-2.1.0-buster
-          context:
-            - qa
-      - qa-core:
-          name: qa-core-celery-2.1.0-buster
-          airflow_version: 2.1.0
-          executor_type: "celery"
-          test_type: "core"
-          requires:
-            - waiter-2.1.0-buster
-          context:
-            - qa
-      - qa-k8s:
-          name: qa-k8s-celery-2.1.0-buster
-          airflow_version: 2.1.0
-          executor_type: "celery"
-          test_type: "k8s"
-          requires:
-            - qa-core-celery-2.1.0-buster
-          context:
-            - qa
-      - qa-params:
-          name: qa-params-celery-2.1.0-buster
-          airflow_version: 2.1.0
-          executor_type: "celery"
-          test_type: "dagparams"
-          requires:
-            - qa-core-celery-2.1.0-buster
-          context:
-            - qa
-      - qa-restapi:
-          name: qa-restapi-celery-2.1.0-buster
-          airflow_version: 2.1.0
-          executor_type: "celery"
-          test_type: "rest"
-          requires:
-            - waiter-2.1.0-buster
-          context:
-            - qa
-      - qa-restapi:
-          name: qa-restapi-local-2.1.0-buster
-          airflow_version: 2.1.0
-          executor_type: "local"
-          test_type: "rest"
-          requires:
-            - qa-restapi-celery-2.1.0-buster
-          context:
-            - qa
-      - qa-restapi:
-          name: qa-restapi-k8s-2.1.0-buster
-          airflow_version: 2.1.0
-          executor_type: "kubernetes"
-          test_type: "rest"
-          requires:
-            - qa-restapi-local-2.1.0-buster
-          context:
-            - qa
-      - qa-core:
-          name: qa-core-k8s-2.1.0-buster
-          airflow_version: 2.1.0
-          executor_type: "kubernetes"
-          test_type: "core"
-          requires:
-            - waiter-2.1.0-buster
-          context:
-            - qa
-      - qa-k8s:
-          name: qa-k8s-k8s-2.1.0-buster
-          airflow_version: 2.1.0
-          executor_type: "kubernetes"
-          test_type: "k8"
-          requires:
-            - qa-core-k8s-2.1.0-buster
-          context:
-            - qa
-      - qa-params:
-          name: qa-params-k8s-2.1.0-buster
-          airflow_version: 2.1.0
-          executor_type: "kubernetes"
-          test_type: "dagparams"
-          requires:
-            - qa-k8s-k8s-2.1.0-buster
-          context:
-            - qa
-      - qa-negative:
-          name: qa-negative-k8s-2.1.0-buster
-          airflow_version: 2.1.0
-          executor_type: "kubernetes"
-          test_type: "negative"
-          requires:
-            - qa-params-k8s-2.1.0-buster
-          context:
-            - qa
-      - qa-core:
-          name: qa-core-local-2.1.0-buster
-          airflow_version: 2.1.0
-          executor_type: "local"
-          test_type: "core"
-          requires:
-            - waiter-2.1.0-buster
-          context:
-            - qa
-  regression-2.1.1-buster:
-    jobs:
-      - waiter:
-          name: waiter-2.1.1-buster
-          airflow_version: 2.1.1
-          context:
-            - qa
-      - qa-ui:
-          name: qa-ui-regression-celery-2.1.1-buster
-          airflow_version: 2.1.1
-          executor_type: "celery"
-          test_type: "testim"
-          requires:
-            - waiter-2.1.1-buster
-          context:
-            - qa
-      - qa-ui:
-          name: qa-ui-regression-k8s-2.1.1-buster
-          airflow_version: 2.1.1
-          executor_type: "kubernetes"
-          test_type: "testim"
-          requires:
-            - qa-ui-regression-celery-2.1.1-buster
-          context:
-            - qa
-      - qa-ui:
-          name: qa-ui-regression-local-2.1.1-buster
-          airflow_version: 2.1.1
-          executor_type: "local"
-          test_type: "testim"
-          requires:
-            - qa-ui-regression-k8s-2.1.1-buster
-          context:
-            - qa
-      - qa-core:
-          name: qa-core-celery-2.1.1-buster
-          airflow_version: 2.1.1
-          executor_type: "celery"
-          test_type: "core"
-          requires:
-            - waiter-2.1.1-buster
-          context:
-            - qa
-      - qa-k8s:
-          name: qa-k8s-celery-2.1.1-buster
-          airflow_version: 2.1.1
-          executor_type: "celery"
-          test_type: "k8s"
-          requires:
-            - qa-core-celery-2.1.1-buster
-          context:
-            - qa
-      - qa-params:
-          name: qa-params-celery-2.1.1-buster
-          airflow_version: 2.1.1
-          executor_type: "celery"
-          test_type: "dagparams"
-          requires:
-            - qa-core-celery-2.1.1-buster
-          context:
-            - qa
-      - qa-restapi:
-          name: qa-restapi-celery-2.1.1-buster
-          airflow_version: 2.1.1
-          executor_type: "celery"
-          test_type: "rest"
-          requires:
-            - waiter-2.1.1-buster
-          context:
-            - qa
-      - qa-restapi:
-          name: qa-restapi-local-2.1.1-buster
-          airflow_version: 2.1.1
-          executor_type: "local"
-          test_type: "rest"
-          requires:
-            - qa-restapi-celery-2.1.1-buster
-          context:
-            - qa
-      - qa-restapi:
-          name: qa-restapi-k8s-2.1.1-buster
-          airflow_version: 2.1.1
-          executor_type: "kubernetes"
-          test_type: "rest"
-          requires:
-            - qa-restapi-local-2.1.1-buster
-          context:
-            - qa
-      - qa-core:
-          name: qa-core-k8s-2.1.1-buster
-          airflow_version: 2.1.1
-          executor_type: "kubernetes"
-          test_type: "core"
-          requires:
-            - waiter-2.1.1-buster
-          context:
-            - qa
-      - qa-k8s:
-          name: qa-k8s-k8s-2.1.1-buster
-          airflow_version: 2.1.1
-          executor_type: "kubernetes"
-          test_type: "k8"
-          requires:
-            - qa-core-k8s-2.1.1-buster
-          context:
-            - qa
-      - qa-params:
-          name: qa-params-k8s-2.1.1-buster
-          airflow_version: 2.1.1
-          executor_type: "kubernetes"
-          test_type: "dagparams"
-          requires:
-            - qa-k8s-k8s-2.1.1-buster
-          context:
-            - qa
-      - qa-negative:
-          name: qa-negative-k8s-2.1.1-buster
-          airflow_version: 2.1.1
-          executor_type: "kubernetes"
-          test_type: "negative"
-          requires:
-            - qa-params-k8s-2.1.1-buster
-          context:
-            - qa
-      - qa-core:
-          name: qa-core-local-2.1.1-buster
-          airflow_version: 2.1.1
-          executor_type: "local"
-          test_type: "core"
-          requires:
-            - waiter-2.1.1-buster
-          context:
-            - qa
   regression-2.1.3-buster:
     jobs:
       - waiter:
@@ -542,6 +10,11 @@ workflows:
           airflow_version: 2.1.3
           context:
             - qa
+          filters:
+            branches:
+              only:
+                - master
+                - waiter_for_each_airflowv
       - qa-ui:
           name: qa-ui-regression-celery-2.1.3-buster
           airflow_version: 2.1.3
@@ -2435,19 +1908,20 @@ jobs:
             cd /home/circleci/project/qa-regression/postman_rest
             chmod 744 restapi_executor_ci.sh
             bash ./restapi_executor_ci.sh
+            curl -X POST -H "Content-Type: text/xml" -H "Authorization: Bearer $RESTAPI_TESULTS_TOKEN" -d /home/circleci/project/qa-regression/results.xml https://www.tesults.com/results
             cp result.out /tmp/test-results/restapi/
-            #FOUND_404=0
-            #FOUND_500=0
-            #ASSERTION_ERRORS=0
-            #grep -q "404 Not Found" result.out && FOUND_404=1
-            #grep -q "500 INTERNAL SERVER ERROR" result.out && FOUND_500=1
-            #grep -q "AssertionError" result.out && ASSERTION_ERRORS=1
-            #if [[ "$FOUND_404" -eq 1 ]]; then echo "404 Errors Found";exit 1; fi
-            #if [[ "$FOUND_500" -eq 1 ]]; then echo "500 Errors Found";exit 1; fi
-            #if [[ "$ASSERTION_ERRORS" -eq 1 ]]; then echo "Assertion Errors Found";exit 1; fi
-            #cd /home/circleci/project/qa-regression
-            #chmod 744 delete_deployment.sh
-            #bash ./delete_deployment.sh
+            FOUND_404=0
+            FOUND_500=0
+            ASSERTION_ERRORS=0
+            grep -q "404 Not Found" result.out && FOUND_404=1
+            grep -q "500 INTERNAL SERVER ERROR" result.out && FOUND_500=1
+            grep -q "AssertionError" result.out && ASSERTION_ERRORS=1
+            if [[ "$FOUND_404" -eq 1 ]]; then echo "404 Errors Found";exit 1; fi
+            if [[ "$FOUND_500" -eq 1 ]]; then echo "500 Errors Found";exit 1; fi
+            if [[ "$ASSERTION_ERRORS" -eq 1 ]]; then echo "Assertion Errors Found";exit 1; fi
+            cd /home/circleci/project/qa-regression
+            chmod 744 delete_deployment.sh
+            bash ./delete_deployment.sh
       - store_artifacts:
           path: /tmp/test-results
       - store_test_results:
diff --git a/.circleci/config.yml.j2 b/.circleci/config.yml.j2
--- a/.circleci/config.yml.j2
+++ b/.circleci/config.yml.j2
@@ -7,6 +7,7 @@ workflows:
 {%- set dev_build = "true" if "dev" in ac_version else "false" -%}
 {%- for distribution in distributions %}
     {%- if airflow_version|checkair2 == true %}
+    {%- if dev_build == "true" %}
   regression-{{ airflow_version }}-{{ distribution }}:
     jobs:
       - waiter:
@@ -14,6 +15,11 @@ workflows:
           airflow_version: {{ airflow_version }}
           context:
             - qa
+          filters:
+            branches:
+              only:
+                - master
+                - waiter_for_each_airflowv
       - qa-ui:
           name: qa-ui-regression-celery-{{ airflow_version }}-{{ distribution }}
           airflow_version: {{ airflow_version }}
@@ -140,7 +146,8 @@ workflows:
             - waiter-{{ airflow_version }}-{{ distribution }}
           context:
             - qa
-    {%- endif %}
+        {%- endif %}
+        {%- endif %}
 {%- endfor %}
 {%- endfor %}
   certified-airflow:
@@ -551,19 +558,20 @@ jobs:
             cd /home/circleci/project/qa-regression/postman_rest
             chmod 744 restapi_executor_ci.sh
             bash ./restapi_executor_ci.sh
+            curl -X POST -H "Content-Type: text/xml" -H "Authorization: Bearer $RESTAPI_TESULTS_TOKEN" -d /home/circleci/project/qa-regression/results.xml https://www.tesults.com/results
             cp result.out /tmp/test-results/restapi/
-            #FOUND_404=0
-            #FOUND_500=0
-            #ASSERTION_ERRORS=0
-            #grep -q "404 Not Found" result.out && FOUND_404=1
-            #grep -q "500 INTERNAL SERVER ERROR" result.out && FOUND_500=1
-            #grep -q "AssertionError" result.out && ASSERTION_ERRORS=1
-            #if [[ "$FOUND_404" -eq 1 ]]; then echo "404 Errors Found";exit 1; fi
-            #if [[ "$FOUND_500" -eq 1 ]]; then echo "500 Errors Found";exit 1; fi
-            #if [[ "$ASSERTION_ERRORS" -eq 1 ]]; then echo "Assertion Errors Found";exit 1; fi
-            #cd /home/circleci/project/qa-regression
-            #chmod 744 delete_deployment.sh
-            #bash ./delete_deployment.sh
+            FOUND_404=0
+            FOUND_500=0
+            ASSERTION_ERRORS=0
+            grep -q "404 Not Found" result.out && FOUND_404=1
+            grep -q "500 INTERNAL SERVER ERROR" result.out && FOUND_500=1
+            grep -q "AssertionError" result.out && ASSERTION_ERRORS=1
+            if [[ "$FOUND_404" -eq 1 ]]; then echo "404 Errors Found";exit 1; fi
+            if [[ "$FOUND_500" -eq 1 ]]; then echo "500 Errors Found";exit 1; fi
+            if [[ "$ASSERTION_ERRORS" -eq 1 ]]; then echo "Assertion Errors Found";exit 1; fi
+            cd /home/circleci/project/qa-regression
+            chmod 744 delete_deployment.sh
+            bash ./delete_deployment.sh
       - store_artifacts:
           path: /tmp/test-results
       - store_test_results:
