Disable Job Stop on Failures

diff --git a/.circleci/config.yml.j2 b/.circleci/config.yml.j2
--- a/.circleci/config.yml.j2
+++ b/.circleci/config.yml.j2
@@ -566,9 +566,9 @@ jobs:
             grep -q "404 Not Found" result.out && FOUND_404=1
             grep -q "500 INTERNAL SERVER ERROR" result.out && FOUND_500=1
             grep -q "AssertionError" result.out && ASSERTION_ERRORS=1
-            if [[ "$FOUND_404" -eq 1 ]]; then echo "404 Errors Found";exit 1; fi
-            if [[ "$FOUND_500" -eq 1 ]]; then echo "500 Errors Found";exit 1; fi
-            if [[ "$ASSERTION_ERRORS" -eq 1 ]]; then echo "Assertion Errors Found";exit 1; fi
+            #if [[ "$FOUND_404" -eq 1 ]]; then echo "404 Errors Found";exit 1; fi
+            #if [[ "$FOUND_500" -eq 1 ]]; then echo "500 Errors Found";exit 1; fi
+            #if [[ "$ASSERTION_ERRORS" -eq 1 ]]; then echo "Assertion Errors Found";exit 1; fi
             cd /home/circleci/project/qa-regression
             chmod 744 delete_deployment.sh
             bash ./delete_deployment.sh
