modify to add deletedeployments

diff --git a/.circleci/config.yml.j2 b/.circleci/config.yml.j2
--- a/.circleci/config.yml.j2
+++ b/.circleci/config.yml.j2
@@ -70,7 +70,7 @@ workflows:
           dev_build: {{ dev_build }}
           extra_tags: "{{ airflow_version }}-{{ distribution }}-onbuild-${CIRCLE_BUILD_NUM}"
           executor_type: "celery"
-          test_type: "core"
+          test_type: "k8s"
           requires:
             - qa-core-celery-{{ airflow_version }}-{{ distribution }}
       - qa-restapi:
@@ -79,7 +79,7 @@ workflows:
           dev_build: {{ dev_build }}
           extra_tags: "{{ airflow_version }}-{{ distribution }}-onbuild-${CIRCLE_BUILD_NUM}"
           executor_type: "celery"
-          test_type: "core"
+          test_type: "rest"
           requires:
             - waiter
       # - qa-core:
@@ -302,7 +302,7 @@ jobs:
             cd qa-regression
             ls
             chmod 744 *.sh
-            echo "Run Deployment Script1"
+            echo "Run Deployment Script"
             bash ./create_deployment.sh << parameters.airflow_version >>  << parameters.executor_type >>  << parameters.test_type >>
             cd ..
       - run: mkdir -p $CIRCLE_TEST_REPORTS/testim/
@@ -382,13 +382,20 @@ jobs:
             dags trigger --headers "Authorization":"$QA_CLUSTER_SERVICEACCOUNT" -e $EXEC_TIME -t core
             sleep 240
             echo "Sleeping for 240s"
-            dags results -e $EXEC_TIME --headers "Authorization":"Bearer $QA_CLUSTER_SERVICEACCOUNT"
+            dags results -e $EXEC_TIME --headers "Authorization":"Bearer $QA_CLUSTER_SERVICEACCOUNT" > /tmp/test-results/results_core_dags.out
+            FOUND_FAILURES=0
+            grep -q "failed" /tmp/test-results/results_core_dags.out && FOUND_FAILURES=1
+            cat /tmp/test-results/results_core_dags.out
+            if [[ "$FOUND_FAILURES" -eq 1 ]]; then echo "DAG Failures Found";exit 1; fi
+            cd /home/circleci/project/qa-regression
+            chmod 744 delete_deployment.sh
+            bash ./delete_deployment.sh
       - store_artifacts:
           path: /tmp/test-results
       - store_test_results:
           path: /tmp/test-results
       - persist_to_workspace:
-          root: .
+          root: ~/
           paths:
             - project
   qa-restapi:
@@ -447,10 +454,16 @@ jobs:
             cp result.out /tmp/test-results/restapi/
             FOUND_404=0
             FOUND_500=0
+            ASSERTION_ERRORS=0
             grep -q "404 Not Found" result.out && FOUND_404=1
             grep -q "500 INTERNAL SERVER ERROR" result.out && FOUND_500=1
+            grep -q "AssertionError" result.out && ASSERTION_ERRORS=1
             if [[ "$FOUND_404" -eq 1 ]]; then echo "404 Errors Found";exit 1; fi
             if [[ "$FOUND_500" -eq 1 ]]; then echo "500 Errors Found";exit 1; fi
+            if [[ "$ASSERTION_ERRORS" -eq 1 ]]; then echo "Assertion Errors Found";exit 1; fi
+            cd /home/circleci/project/qa-regression
+            chmod 744 delete_deployment.sh
+            bash ./delete_deployment.sh
       - store_artifacts:
           path: /tmp/test-results
       - store_test_results:
@@ -481,7 +494,7 @@ jobs:
         type: string
     steps:
       - attach_workspace:
-          at: /tmp/workspace
+          at: ~/
       # - run: sudo apt-get -y update
       # - run: sudo apt-get -y install git curl wget libpq-dev nodejs
       # - run: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
@@ -518,12 +531,19 @@ jobs:
             export DAGSTEST_DB_NAME=axsrggsp
             export DAGSTEST_DB_USER=axsrggsp
             export DAGSTEST_DB_PASSWORD=$QA_DAGSTEST_DB_PASSWORD
-            dags connections --headers "Authorization":"Bearer $QA_CLUSTER_SERVICEACCOUNT" -f /home/circleci/project/qa-scenario-dags/airflow_settings.yaml
+            #dags connections --headers "Authorization":"Bearer $QA_CLUSTER_SERVICEACCOUNT" -f /home/circleci/project/qa-scenario-dags/airflow_settings.yaml
             EXEC_TIME=$(date +%FT%TZ)
             dags trigger --headers "Authorization":"$QA_CLUSTER_SERVICEACCOUNT" -e $EXEC_TIME -t k8s
             sleep 240
             echo "Sleeping for 240s"
-            dags results -e $EXEC_TIME --headers "Authorization":"Bearer $QA_CLUSTER_SERVICEACCOUNT"
+            dags results -e $EXEC_TIME --headers "Authorization":"Bearer $QA_CLUSTER_SERVICEACCOUNT" > $CORE_TEST_REPORTS/k8s/results_k8s_dags.out
+            FOUND_FAILURES=0
+            grep -q "failed" /tmp/test-results/results_k8s_dags.out && FOUND_FAILURES=1
+            cat /tmp/test-results/results_k8s_dags.out
+            if [[ "$FOUND_FAILURES" -eq 1 ]]; then echo "DAG Failures Found1";exit 1; fi
+            cd /home/circleci/project/qa-regression
+            chmod 744 delete_deployment.sh
+            bash ./delete_deployment.sh
       - store_artifacts:
           path: /tmp/test-results
       - store_test_results:
